version: '3.9'

services:
  postgres:
    image: ankane/pgvector:latest 
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpassword
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
